defaults:
  - default@
  - _self_

paths:
  input_dir_SDS: /storage/archive/UCPH/DeepFetal/SDS/registers_pseudonymized
  input_dir_SP: /storage/archive/UCPH/DeepFetal/SP/tables
  output_dir: ${oc.env:EHR_EXTRACT_OUTPUTS}/${hydra:job.config_name}
  population_save_path: ${paths.output_dir}/${hydra:job.config_name}_population
  discards_save_path: ${paths.output_dir}/${hydra:job.config_name}_discards
  distribution_save_path: ${paths.output_dir}/${hydra:job.config_name}_distribution
  imaging_table: /projects/users/data/UCPH/DeepFetal/ultrasound/tables/database_snapshots/all_images_2026-06-23.csv
  # holdout_csv: null

strict: True

population:
  population_key: CPR_BARN
  split_key: CPR_MOR
  file_path_key: FILE_PATH
  deduplication_key: CPR_BARN
  tables:
    - table: ${paths.input_dir_SDS}/mfr.csv
      columns:
        CPR_BARN: CPR_BARN
        CPR_MOR: CPR_MODER
        GA: GESTATIONSALDER_DAGE
        BIRTHDAY: FOEDSELSDATO
    - table: ${paths.input_dir_SDS}/nyfoedte.csv
      columns:
        CPR_BARN: CPRnummer_Barn
        CPR_MOR: CPRnummer_Mor
        GA: Gestationsalder
        BIRTHDAY: FoedselsDato_Barn

imaging_table:
  table: ${paths.imaging_table}
  columns:
    CPR_MOR: phair_hash
    FILE_PATH: file_path
    STUDY_DATE: study_date

imaging_matching_criteria:
  - function: find_images_within_time_windows
    args:
      scan_date_column: STUDY_DATE
      image_path_column: ${population.file_path_key}
      population_ga_in_days_at_delivery_column: GA
      population_delivery_date_column: BIRTHDAY
      min_diff_days_scan_to_delivery: 0
      max_diff_days_scan_to_delivery: 99999
      min_ga_in_days_at_scan: 126
      max_ga_in_days_at_scan: 155
  - function: find_images_on_or_after_date
    args:
      date_column: STUDY_DATE
      min_date: "2019-01-01"
