# @package _global_
defaults:
  - /default@
  - SL_EHR_SP_SDS_noMP_img_V5@
  - _self_

paths:
  input_dir_SDS: /Users/zcr545/Desktop/Projects/repos/ehr2meds/data/raw/fetal_data/SDS_AND_SP_from_population
  input_dir_SP: /Users/zcr545/Desktop/Projects/repos/ehr2meds/data/raw/fetal_data/SDS_AND_SP_from_population
  population: /Users/zcr545/Desktop/Projects/repos/EHR_extract/outputs/test_preterm/test_preterm_population_train_and_test.csv
  output_dir: /Users/zcr545/Desktop/Projects/repos/EHR_extract/outputs/${hydra:job.config_name}
  table_save_path: ${paths.output_dir}/table_${hydra:job.config_name}.csv
  summary_save_path: ${paths.output_dir}/summary_${hydra:job.config_name}.csv
  discards_save_path: ${paths.output_dir}/discards_${hydra:job.config_name}.json

allow_duplicates: True