defaults:
  - default@
  - _self_

paths:
  input_dir_SDS: /storage/archive/UCPH/DeepFetal/SDS/registers_pseudonymized
  input_dir_SP: /storage/archive/UCPH/DeepFetal/SP/tables
  output_dir: ${oc.env:EHR_EXTRACT_OUTPUTS}/${hydra:job.config_name}
  population_save_path: ${paths.output_dir}/${hydra:job.config_name}_population
  discards_save_path: ${paths.output_dir}/${hydra:job.config_name}_discards
  distribution_save_path: ${paths.output_dir}/${hydra:job.config_name}_distribution
  holdout_csv: /projects/users/data/UCPH/DeepFetal/projects/common/splits/splits/split_V3/test_split_0.05_2026-04-27.csv

strict: True

population: 
  population_key: CPR_BARN
  split_key: CPR_MOR
  file_path_key: FILE_PATH
  tables: 
    - table: ${paths.input_dir_SDS}/mfr.csv
      columns:
        CPR_BARN: CPR_BARN
        CPR_MOR: CPR_MODER
        GA: GESTATIONSALDER_DAGE
        BIRTHDAY: FOEDSELSDATO
    - table: ${paths.input_dir_SDS}/nyfoedte.csv
      columns:
        CPR_BARN: CPRnummer_Barn
        CPR_MOR: CPRnummer_Mor
        GA: Gestationsalder
        BIRTHDAY: FoedselsDato_Barn
  composed_tables:
    - merge_on: CPR_BARN
      format_SP_GA: True
      tables:
        - table: ${paths.input_dir_SP}/Population.csv
          columns:
            CPR_BARN: BABY_CPR
            CPR_MOR: MOR_CPR
            BIRTHDAY: Fødselstidspunkt
        - table: ${paths.input_dir_SP}/Barn - Fødselsinfo.csv
          columns:
            CPR_BARN: BABY_CPR
            GA: Gestationsalder

imaging_table:
  table: /projects/users/people/seblla/repos/EHR_extract/all_images_2026-04-27.csv
  columns:
    CPR_MOR: phair_hash
    FILE_PATH: file_path
    STUDY_DATE: study_date
    PDX: physical_delta_x
    PDY: physical_delta_y
    NO_OCR_FILE_PATH: no_ocr_preprocessed_file_path

conditional_criteria:
  # GA available at birth
  - action: include
    conditions: 
      - condition: 
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: GESTATIONSALDER_DAGE
        operator: "not_null"
        value: 
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Gestationsalder
        operator: "not_null"
        value: 
      - condition: 
        table: ${paths.input_dir_SP}/Barn - Fødselsinfo.csv
        match_on: BABY_CPR
        column: Gestationsalder
        operator: "not_null"
        value: 
  # Only first pregnancy (no SP)
  - action: exclude
    conditions:
      - condition: 
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: PARITET
        operator: "!="
        value: "1"
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Paritet
        operator: "!="
        value: "1"
  # Only live birth (no SP)
  - action: exclude
    conditions:
      - condition: 
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: LEVENDE_ELLER_DOEDFOEDT
        operator: "!="
        value: Levendefødt
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: LevendefoedtDoedfoedt
        operator: "!="
        value: "1"
  # No C-section/kejsersnit (SP in custom criteria)
  - action: exclude
    conditions:
      - condition:
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Kejsersnit
        operator: "!="
        value: "-1"
      - condition: or
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: MARKOER_KEJSERSNIT
        operator: "=="
        value: "1"
  # Not induced (SP in custom criteria)
  - action: exclude
    conditions:
      - condition:
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: MARKOER_IGANGSAETTELSE
        operator: "=="
        value: "1"
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Igangsaettelse_Ballonkateter
        operator: "=="
        value: "Ja"
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Igangsaettelse_Medicinsk
        operator: "=="
        value: "Ja"
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Igangsaettelse_HSP
        operator: "=="
        value: "Ja"

custom_criteria:
  # C-section SP 
  - function: match_value_with_child_cpr_on_birthdate
    args:
      value: "KMCA00"
      operator: startswith
      value_table_path: ${paths.input_dir_SP}/Mor - CPMI - Procedurer.csv
      value_column: ProcedureCode
      value_time_column: ServiceDatetime
      value_mother_cpr_column: MOR_CPR
      population_birth_column: BIRTHDAY
      population_gestational_age_column: GA
      population_child_cpr_column: CPR_BARN
      population_mother_cpr_column: CPR_MOR
    action: exclude
  # induction SP
  - function: match_value_with_child_cpr_on_birthdate
    args:
      value: ["KMAC00" , "KMAC96A", "BKHD2", "BKHD20"]
      operator: "=="
      value_table_path: ${paths.input_dir_SP}/Mor - CPMI - Procedurer.csv
      value_column: ProcedureCode
      value_time_column: ServiceDatetime
      value_mother_cpr_column: MOR_CPR
      population_birth_column: BIRTHDAY
      population_gestational_age_column: GA
      population_child_cpr_column: CPR_BARN
      population_mother_cpr_column: CPR_MOR
    action: exclude
  # induction SP continued
  - function: match_value_with_child_cpr_on_birthdate
    args:
      value: ["DO837" , "DO847"]
      operator: startswith
      value_table_path: ${paths.input_dir_SP}/Mor - CPMI - Diagnoseliste.csv
      value_column: Diagnosekode
      value_time_column: Noteret_dato
      value_mother_cpr_column: MOR_CPR
      population_birth_column: BIRTHDAY
      population_gestational_age_column: GA
      population_child_cpr_column: CPR_BARN
      population_mother_cpr_column: CPR_MOR
    action: exclude
  # induction SP continued
  - function: match_value_with_child_cpr_on_birth_id
    args:
      value: ["Vaginal, igangsat", "Vaginal, igangsat (Udgået)"]
      operator: "=="
      value_table_path: ${paths.input_dir_SP}/Mor - Fødselsresume - DEL 1.csv
      value_column: Måde
      value_table_birth_id_column: BABY_Fødsel_ID
      mapping_table_path: ${paths.input_dir_SP}/Population.csv
      mapping_table_birth_id_column: BABY_Fødsel_ID
      mapping_table_child_cpr_column: BABY_CPR
    action: exclude
  # Remove multiple (twin etc.) births (no SP)
  - function: find_multiple_births
    args: 
      table: ${paths.input_dir_SDS}/nyfoedte.csv
      match_on: CPRnummer_Barn
      birth_id_column: DW_EK_Foedsel
    action: exclude
  - function: find_multiple_births
    args: 
      table: ${paths.input_dir_SDS}/mfr.csv
      match_on: CPR_BARN
      birth_id_column: FOEDSELSLOEBENUMMER
    action: exclude
  # Removes close pregnancies (no SP)
  - function: find_close_births
    args:
      table: ${paths.input_dir_SDS}/nyfoedte.csv
      match_on: CPRnummer_Barn
      mom_column: CPRnummer_Mor
      birth_id_column: DW_EK_Foedsel
      delivery_date_column: FoedselsDato_Barn
      threshold_days: 280
    action: exclude
  - function: find_close_births
    args:
      table: ${paths.input_dir_SDS}/mfr.csv
      match_on: CPR_BARN
      mom_column: CPR_MODER
      birth_id_column: FOEDSELSLOEBENUMMER
      delivery_date_column: FOEDSELSDATO
      threshold_days: 280
    action: exclude
    
imaging_matching_criteria:
  # Filter1: Scan-to-delivery interval
  # Filter2: GA at scan
  - function: find_images_within_time_windows
    args: 
      scan_date_column: STUDY_DATE
      image_path_column: ${population.file_path_key}
      population_ga_in_days_at_delivery_column: GA
      population_delivery_date_column: BIRTHDAY
      min_diff_days_scan_to_delivery: 0 #0
      max_diff_days_scan_to_delivery: 210 #210
      min_ga_in_days_at_scan: 196 #196
      max_ga_in_days_at_scan: 259 #259
  # Only Cervix (14)
  - function: find_images_with_predicted_classes
    args:
      table: /projects/users/data/UCPH/DeepFetal/projects/common/PN_plane_classification_april2026/Cervix_preds_v1/cervix_preds.csv
      classes: [14]
      image_path_column: file_path
      class_column: pred
      population_image_path_column: ${population.file_path_key}
    

