defaults:
  - default@
  - preterm_SP_P1_v2@
  - _self_

paths:
  input_dir_SDS: /storage/archive/UCPH/DeepFetal/SDS/registers_pseudonymized
  input_dir_SP: /storage/archive/UCPH/DeepFetal/SP/tables
  output_dir: ${oc.env:EHR_EXTRACT_OUTPUTS}/${hydra:job.config_name}
  population_save_path: ${paths.output_dir}/${hydra:job.config_name}_population
  discards_save_path: ${paths.output_dir}/${hydra:job.config_name}_discards
  distribution_save_path: ${paths.output_dir}/${hydra:job.config_name}_distribution
  holdout_csv: /projects/users/data/UCPH/DeepFetal/projects/common/splits/splits/split_V3/test_split_0.05_2026-04-27.csv


conditional_criteria:
  # GA available at birth
  - action: exclude
    conditions: 
      - condition: 
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: GESTATIONSALDER_DAGE
        operator: "missing"
        value: 
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Gestationsalder
        operator: "missing"
        value: 
      - condition: or
        table: ${paths.input_dir_SP}/Barn - Fødselsinfo.csv
        match_on: BABY_CPR
        column: Gestationsalder
        operator: "missing"
        value: 
  # Only first pregnancy (no SP)
  - action: exclude
    conditions:
      - condition: 
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: PARITET
        operator: "!="
        value: "1"
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Paritet
        operator: "!="
        value: "1"
  # Only live birth (no SP)
  - action: exclude
    conditions:
      - condition: 
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: LEVENDE_ELLER_DOEDFOEDT
        operator: "!="
        value: Levendefødt
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: LevendefoedtDoedfoedt
        operator: "!="
        value: "1"
  # No C-section/kejsersnit (SP in custom criteria)
  - action: exclude
    conditions:
      - condition:
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Kejsersnit
        operator: "!="
        value: "-1"
      - condition: and
        table: population
        match_on: CPR_BARN
        column: GA
        operator: <
        value: ${preterm_cutoff}
      - condition: or
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: MARKOER_KEJSERSNIT
        operator: "=="
        value: "1"
      - condition: and
        table: population
        match_on: CPR_BARN
        column: GA
        operator: <
        value: ${preterm_cutoff}
  # Not induced (SP in custom criteria)
  - action: exclude
    conditions:
      - condition:
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: MARKOER_IGANGSAETTELSE
        operator: "=="
        value: "1"
      - condition: and
        table: population
        match_on: CPR_BARN
        column: GA
        operator: <
        value: ${preterm_cutoff}
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Igangsaettelse_Ballonkateter
        operator: "=="
        value: "Ja"
      - condition: and
        table: population
        match_on: CPR_BARN
        column: GA
        operator: <
        value: ${preterm_cutoff}
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Igangsaettelse_Medicinsk
        operator: "=="
        value: "Ja"
      - condition: and
        table: population
        match_on: CPR_BARN
        column: GA
        operator: <
        value: ${preterm_cutoff}
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Igangsaettelse_HSP
        operator: "=="
        value: "Ja"
      - condition: and
        table: population
        match_on: CPR_BARN
        column: GA
        operator: <
        value: ${preterm_cutoff}
        
custom_criteria:
  # C-section SP 
  - function: match_value_with_child_cpr_on_birthdate_if_ga_below_threshold
    args:
      value: "KMCA"
      operator: startswith
      value_table_path: ${paths.input_dir_SP}/Mor - CPMI - Procedurer.csv
      value_column: ProcedureCode
      value_time_column: ServiceDatetime
      value_mother_cpr_column: MOR_CPR
      population_birth_column: BIRTHDAY
      population_gestational_age_column: GA
      population_child_cpr_column: CPR_BARN
      population_mother_cpr_column: CPR_MOR
      ga_threshold: ${preterm_cutoff}
    action: exclude
  # induction SP
  - function: match_value_with_child_cpr_on_birthdate_if_ga_below_threshold
    args:
      value: ["KMAC00" , "KMAC96A", "BKHD2", "BKHD20"]
      operator: "=="
      value_table_path: ${paths.input_dir_SP}/Mor - CPMI - Procedurer.csv
      value_column: ProcedureCode
      value_time_column: ServiceDatetime
      value_mother_cpr_column: MOR_CPR
      population_birth_column: BIRTHDAY
      population_gestational_age_column: GA
      population_child_cpr_column: CPR_BARN
      population_mother_cpr_column: CPR_MOR
      ga_threshold: ${preterm_cutoff}
    action: exclude
  # induction SP continued
  - function: match_value_with_child_cpr_on_birthdate_if_ga_below_threshold
    args:
      value: ["DO837" , "DO847"]
      operator: startswith
      value_table_path: ${paths.input_dir_SP}/Mor - CPMI - Diagnoseliste.csv
      value_column: Diagnosekode
      value_time_column: Noteret_dato
      value_mother_cpr_column: MOR_CPR
      population_birth_column: BIRTHDAY
      population_gestational_age_column: GA
      population_child_cpr_column: CPR_BARN
      population_mother_cpr_column: CPR_MOR
      ga_threshold: ${preterm_cutoff}
    action: exclude
  # induction SP continued
  - function: match_value_with_child_cpr_on_birth_id_if_ga_below_threshold
    args:
      value: ["Vaginal, igangsat", "Vaginal, igangsat (Udgået)"]
      operator: "=="
      value_table_path: ${paths.input_dir_SP}/Mor - Fødselsresume - DEL 1.csv
      value_column: Måde
      value_table_birth_id_column: BABY_Fødsel_ID
      mapping_table_path: ${paths.input_dir_SP}/Population.csv
      mapping_table_birth_id_column: BABY_Fødsel_ID
      mapping_table_child_cpr_column: BABY_CPR
      population_gestational_age_column: GA
      ga_threshold: ${preterm_cutoff}
    action: exclude
  # Removes close pregnancies (no SP)
  - function: find_close_births
    args:
      table: ${paths.input_dir_SDS}/nyfoedte.csv
      match_on: CPRnummer_Barn
      mom_column: CPRnummer_Mor
      birth_id_column: DW_EK_Foedsel
      delivery_date_column: FoedselsDato_Barn
      threshold_days: 280
    action: exclude
  - function: find_close_births
    args:
      table: ${paths.input_dir_SDS}/mfr.csv
      match_on: CPR_BARN
      mom_column: CPR_MODER
      birth_id_column: FOEDSELSLOEBENUMMER
      delivery_date_column: FOEDSELSDATO
      threshold_days: 280
    action: exclude
  # Remove multiple (twin etc.) births (no SP)
  - function: find_multiple_births
    args: 
      table: ${paths.input_dir_SDS}/nyfoedte.csv
      match_on: CPRnummer_Barn
      birth_id_column: DW_EK_Foedsel
    action: exclude
  - function: find_multiple_births
    args: 
      table: ${paths.input_dir_SDS}/mfr.csv
      match_on: CPR_BARN
      birth_id_column: FOEDSELSLOEBENUMMER
    action: exclude
