paths:
  input_dir_SDS: ${oc.env:EHR_EXTRACT_DATA}/SDS/registers_pseudonymized
  input_dir_SP: ${oc.env:EHR_EXTRACT_DATA}/SP/tables
  population: outputs/populations/full_population.json
  output_dir: outputs/tables
  table_save_path: ${paths.output_dir}/table_${hydra:job.config_name}.json
  summary_save_path: ${paths.output_dir}/summary_${hydra:job.config_name}.json
  discards_save_path: ${paths.output_dir}/discards_${hydra:job.config_name}.json

strict: True 

summary_table: 
  make_table: True
  ignore_columns: [b_cpr, m_cpr, pregnancy_end, pregnancy_start]
  n_samples: 100000

base_table: 
  population: ${paths.population}
  population_column: b_cpr
  tables:
    - table: ${paths.input_dir_SDS}/mfr.csv
      columns: {CPR_MODER: m_cpr, FOEDSELSDATO: pregnancy_end, GESTATIONSALDER_DAGE: GA_days, CPR_BARN: b_cpr}
    - table: ${paths.input_dir_SDS}/nyfoedte.csv
      columns: {CPRnummer_Mor: m_cpr, CPRnummer_Barn: b_cpr, Gestationsalder: GA_days, FoedselsDato_Barn: pregnancy_end}
  key_columns: [b_cpr, m_cpr, GA_days, pregnancy_end]
  dtypes: {b_cpr: string, m_cpr: string, GA_days: string, pregnancy_end: date}
  add_columns:
    - column: pregnancy_start
      function: find_pregnancy_start
      args:
        birth_date_col: pregnancy_end
        GA_days_col: GA_days
        pregnancy_start_col: pregnancy_start
    - column: GA_weeks
      function: find_GA_weeks
      args:
        GA_days_col: GA_days
        GA_weeks_col: GA_weeks

time_conditionals:
  before_pregnancy:
    min_date:
      date_col: null
      offset_days: 0
    max_date:
      date_col: pregnancy_start
      offset_days: -1
  during_pregnancy:
    min_date:
      date_col: pregnancy_start
      offset_days: 0
    max_date:
      date_col: pregnancy_end
      offset_days: 0
  year_before_pregnancy:
    min_date:
      date_col: pregnancy_start
      offset_days: -365
    max_date:
      date_col: pregnancy_start
      offset_days: 0


extract_criteria:
  - name: ethnicity
    key_column: m_cpr
    sources:
      - table: ${paths.input_dir_SDS}/indvandrer_efterkommer.csv
        match_on: V_PNR
        column: oprindelses_land_tekst
    dtype: string
  - name: maternal_age
    key_column: b_cpr
    sources:
      - table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: ALDER_MODER
      - table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Alder_Mor
    dtype: integer
  - name: maternal_BMI
    key_column: b_cpr
    sources:
      - table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: BMI_MODER
      - table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: BMI_Mor
    dtype: float
  - name: smoking_status
    key_column: b_cpr
    sources:
      - table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: RYGERSTATUS_MODER
      - table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Tobaksforbrug
    dtype: string
  - name: parity
    key_column: b_cpr
    sources:
      - table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: PARITET
      - table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Paritet
    dtype: string

conditional_criteria:
  - name: fertility_treatment
    key_column: b_cpr
    match_on: m_cpr
    time_window: year_before_pregnancy
    conditions:
      - condition:
        table: 
          table1: ${paths.input_dir_SDS}/ivf_behandlingsforloeb.csv
          table2: ${paths.input_dir_SDS}/nyfoedte.csv
          left_on: CPRnummer
          right_on: CPRnummer_Mor
        match_on: CPRnummer
        column: Graviditet
        operator: "=="
        value: "Ja"
        date_col: Transferering_dato
      - condition: or
        table: 
          table1: ${paths.input_dir_SDS}/ivf_behandlingsforloeb.csv
          table2: ${paths.input_dir_SDS}/mfr.csv
          left_on: CPRnummer
          right_on: CPR_MODER
        match_on: CPRnummer
        column: Graviditet
        operator: "=="
        value: "Ja"
        date_col: Transferering_dato
  ### Obstetric history
  # parity
  # previous ptb
  - name: previous_ptb
    key_column: b_cpr
    match_on: m_cpr
    time_window: before_pregnancy
    conditions:
      - condition:
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_MODER
        column: GESTATIONSALDER_DAGE
        operator: "<"
        value: 259
        date_col: FOEDSELSDATO
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Mor
        column: Gestationsalder
        operator: "<"
        value: 259
        date_col: FoedselsDato_Barn
  # previous late_miscarriage
  - name: previous_late_miscarriage
    key_column: b_cpr
    match_on: m_cpr
    time_window: before_pregnancy
    conditions:
      - condition:
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_MODER
        column: GESTATIONSALDER_DAGE
        operator: "<"
        value: 154
        date_col: FOEDSELSDATO
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Mor
        column: Gestationsalder
        operator: "<"
        value: 154
        date_col: FoedselsDato_Barn
      - condition: and
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_MODER
        column: GESTATIONSALDER_DAGE
        operator: ">"
        value: 84
        date_col: FOEDSELSDATO
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Mor
        column: Gestationsalder
        operator: ">"
        value: 84
        date_col: FoedselsDato_Barn
  # previous pprom
  - name: previous_pprom
    key_column: b_cpr
    match_on: m_cpr
    time_window: before_pregnancy
    conditions:
      - condition:
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_MODER
        column: PPROM
        operator: "startswith"
        value: ["DO4"]
        date_col: FOEDSELSDATO
      - condition: or
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_MODER
        column: PROM
        operator: "startswith"
        value: ["DO4"]
        date_col: FOEDSELSDATO
      - condition: or
        table:
          table1: ${paths.input_dir_SDS}/mor_diagnoser.csv
          table2: ${paths.input_dir_SDS}/nyfoedte.csv
          left_on: DW_EK_Foedsel
          right_on: DW_EK_Foedsel
        match_on: CPRnummer_Mor
        column: DiagnoseKode
        operator: "startswith"
        value: ["DO422", "DO420", "DO424"]
        date_col: FoedselsDato_Barn
  # previous short_cervix
  # previous c_section
  - name: previous_c_section
    key_column: b_cpr
    match_on: m_cpr
    time_window: before_pregnancy
    conditions:
      - condition:
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_MODER
        column: MARKOER_KEJSERSNIT
        operator: "=="
        value: "1"
        date_col: FOEDSELSDATO
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Mor
        column: Kejsersnit
        operator: "!="
        value: "-1"
        date_col: FoedselsDato_Barn
      - condition: or
        table: 
          table1: ${paths.input_dir_SDS}/kejsersnit.csv
          table2: ${paths.input_dir_SDS}/mfr.csv
          left_on: FK_MFR
          right_on: PK_MFR
        match_on: CPR_MODER
        column: SKSKODE
        operator: "startswith"
        value: ["KMCA"]
        date_col: FOEDSELSDATO
  # previous preclampsia
  - name: previous_preclampsia
    key_column: b_cpr
    match_on: m_cpr
    time_window: before_pregnancy
    conditions:
      - condition:
        table: 
          table1: ${paths.input_dir_SDS}/graviditetskomplikation.csv
          table2: ${paths.input_dir_SDS}/mfr.csv
          left_on: FK_MFR
          right_on: PK_MFR
        match_on: CPR_MODER
        column: SKSKODE
        operator: "startswith"
        value: ["DZ358Q", "DO144", "DO141", "DO140", "DO139"]
        date_col: FOEDSELSDATO
      - condition: or
        table:
          table1: ${paths.input_dir_SDS}/mor_diagnoser.csv
          table2: ${paths.input_dir_SDS}/nyfoedte.csv
          left_on: DW_EK_Foedsel
          right_on: DW_EK_Foedsel
        match_on: CPRnummer_Mor
        column: DiagnoseKode
        operator: "startswith"
        value: ["DZ358Q", "DO144", "DO141", "DO140", "DO139"]
        date_col: FoedselsDato_Barn

  ### Current pregnancy (cervical)
  # cervical conization # TODO: missing mfr2
  - name: current_cervical_conization
    key_column: b_cpr
    match_on: m_cpr
    time_window: during_pregnancy
    conditions:
      - condition:
        table:
          table1: ${paths.input_dir_SDS}/mor_diagnoser.csv
          table2: ${paths.input_dir_SDS}/nyfoedte.csv
          left_on: DW_EK_Foedsel
          right_on: DW_EK_Foedsel
        match_on: CPRnummer_Mor
        column: DiagnoseKode
        operator: "startswith"
        value: ["DZ928C", "DO344B"]
        date_col: FoedselsDato_Barn
      - condition: or
        table:
          table1: ${paths.input_dir_SDS}/mor_procedurer.csv
          table2: ${paths.input_dir_SDS}/nyfoedte.csv
          left_on: DW_EK_Foedsel
          right_on: DW_EK_Foedsel
        match_on: CPRnummer_Mor
        column: ProcedureKode
        operator: "startswith"
        value: ["KLDC00", "KLDC03"]
        date_col: FoedselsDato_Barn
  # cervical length #TODO missing
  # short cervix #TODO missing

  ### Current pregnancy (mechanical)
  # multiple pregnancies
  - name: current_multiple_pregnancies
    key_column: b_cpr
    match_on: b_cpr
    time_window: during_pregnancy
    conditions:
      - condition:
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: FLERFOLDSGRAVIDITET
        operator: "startswith"
        value: "DO30"
        date_col: FOEDSELSDATO
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: AntalBoernIFoedslen
        operator: ">"
        value: 1
        date_col: FoedselsDato_Barn
  # uterine malformation #TODO missing mfr2
  - name: current_uterine_malformation
    key_column: b_cpr
    match_on: b_cpr
    time_window: during_pregnancy
    conditions:
      - condition:
        table:  
          table1: ${paths.input_dir_SDS}/mor_diagnoser.csv
          table2: ${paths.input_dir_SDS}/nyfoedte.csv
          left_on: DW_EK_Foedsel
          right_on: DW_EK_Foedsel
        match_on: CPRnummer_Barn
        column: DiagnoseKode
        operator: "startswith"
        value: ["DO340", "DQ518", "DQ519"]
        date_col: FoedselsDato_Barn
  # fibroids #TODO missing in mfr2
  - name: current_fibroids
    key_column: b_cpr
    match_on: m_cpr
    time_window: during_pregnancy
    conditions:
      - condition: 
        table:
          table1: ${paths.input_dir_SDS}/mor_diagnoser.csv
          table2: ${paths.input_dir_SDS}/nyfoedte.csv
          left_on: DW_EK_Foedsel
          right_on: DW_EK_Foedsel
        match_on: CPRnummer_Mor
        column: DiagnoseKode
        operator: "startswith"
        value: ["DD259", "DD250", "DD250C", "DD251", "DD252", "DD250A", "DD250B", "DO341"]
        date_col: FoedselsDato_Barn
      # - condition: or
      #   table:
      #     table1: ${paths.input_dir_SDS}/graviditetskomplikation.csv
      #     table2: ${paths.input_dir_SDS}/mfr.csv
      #     left_on: FK_MFR
      #     right_on: PK_MFR
      #   match_on: CPR_MODER
      #   column: SKSKODE
      #   operator: "startswith"
      #   value: ["DD259", "DD250", "DD250C", "DD251", "DD252", "DD250A", "DD250B", "DO341"]
      #   date_col: FOEDSELSDATO
  # polyhydramnios
  - name: current_polyhydramnios
    key_column: b_cpr
    match_on: m_cpr
    time_window: during_pregnancy
    conditions:
      - condition:
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_MODER
        column: POLYHYDRAMNIOS
        operator: "startswith"
        value: ["DO4"]
        date_col: FOEDSELSDATO
      - condition: or
        table: 
          table1: ${paths.input_dir_SDS}/mor_diagnoser.csv
          table2: ${paths.input_dir_SDS}/nyfoedte.csv
          left_on: DW_EK_Foedsel
          right_on: DW_EK_Foedsel
        match_on: CPRnummer_Mor
        column: DiagnoseKode
        operator: "startswith"
        value: ["DO410", "DO409"]
        date_col: FoedselsDato_Barn
  ### Current pregnancy (medical)
  # preclampsia
  - name: current_preclampsia
    key_column: b_cpr
    match_on: b_cpr
    time_window: during_pregnancy
    conditions:
      - condition:
        table: 
          table1: ${paths.input_dir_SDS}/graviditetskomplikation.csv
          table2: ${paths.input_dir_SDS}/mfr.csv
          left_on: FK_MFR
          right_on: PK_MFR
        match_on: CPR_BARN
        column: SKSKODE
        operator: "startswith"
        value: ["DZ358Q", "DO144", "DO141", "DO140", "DO139"]
        date_col: FOEDSELSDATO
      - condition: or
        table:
          table1: ${paths.input_dir_SDS}/mor_diagnoser.csv
          table2: ${paths.input_dir_SDS}/nyfoedte.csv
          left_on: DW_EK_Foedsel
          right_on: DW_EK_Foedsel
        match_on: CPRnummer_Barn
        column: DiagnoseKode
        operator: "startswith"
        value: ["DZ358Q", "DO144", "DO141", "DO140", "DO139"]
        date_col: FoedselsDato_Barn
  # vaginal bleeding #TODO missing in mfr2
  - name: current_vaginal_bleeding
    key_column: b_cpr
    match_on: m_cpr
    time_window: during_pregnancy
    conditions:
      - condition:
        table:  
          table1: ${paths.input_dir_SDS}/mor_diagnoser.csv
          table2: ${paths.input_dir_SDS}/nyfoedte.csv
          left_on: DW_EK_Foedsel
          right_on: DW_EK_Foedsel
        match_on: CPRnummer_Mor
        column: DiagnoseKode
        operator: "startswith"
        value: ["DO468A", "DO209", "DO208", "DO208A"]
        date_col: FoedselsDato_Barn
  # infection #TODO missing in mfr2
  - name: current_infection
    key_column: b_cpr
    match_on: b_cpr
    time_window: during_pregnancy
    conditions:
      # - condition:
      #   table: 
      #     table1: ${paths.input_dir_SDS}/infektioner.csv
      #     table2: ${paths.input_dir_SDS}/mfr.csv
      #     left_on: FK_MFR
      #     right_on: PK_MFR
      #   match_on: CPR_BARN
      #   column: SKSKODE
      #   operator: "startswith"
      #   value: ["DO98"]
      #   date_col: FOEDSELSDATO
      - condition: 
        table:
          table1: ${paths.input_dir_SDS}/mor_diagnoser.csv
          table2: ${paths.input_dir_SDS}/nyfoedte.csv
          left_on: DW_EK_Foedsel
          right_on: DW_EK_Foedsel
        match_on: CPRnummer_Barn
        column: DiagnoseKode
        operator: "startswith"
        value: ["DN390A", "DN390", "DA499", "DB349", "DZ038A", "DO234", "DO233", "DO235", "DO239"]
        date_col: FoedselsDato_Barn
  # pprom
  - name: current_pprom
    key_column: b_cpr
    match_on: b_cpr
    time_window: during_pregnancy
    conditions:
      - condition:
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: PPROM
        operator: "startswith"
        value: ["DO4"]
        date_col: FOEDSELSDATO
      - condition: or
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: PROM
        operator: "startswith"
        value: ["DO4"]
        date_col: FOEDSELSDATO
      - condition: or
        table:
          table1: ${paths.input_dir_SDS}/mor_diagnoser.csv
          table2: ${paths.input_dir_SDS}/nyfoedte.csv
          left_on: DW_EK_Foedsel
          right_on: DW_EK_Foedsel
        match_on: CPRnummer_Barn
        column: DiagnoseKode
        operator: "startswith"
        value: ["DO422", "DO420", "DO424"]
        date_col: FoedselsDato_Barn
  # maternal comorbidity #TODO missing in mfr2
  - name: current_maternal_comorbidity
    key_column: b_cpr
    match_on: b_cpr
    time_window: during_pregnancy
    conditions:
      - condition:
        table:  
          table1: ${paths.input_dir_SDS}/mor_diagnoser.csv
          table2: ${paths.input_dir_SDS}/nyfoedte.csv
          left_on: DW_EK_Foedsel
          right_on: DW_EK_Foedsel
        match_on: CPRnummer_Barn
        column: DiagnoseKode
        operator: "startswith"
        value: ["DO998", "DO101", "DZ038O", "DO103", "DO992", "DO993B", "DO994", 
                       "DO102", "DO993", "DO996A", "DO991", "DO995", "DO993A", "DO997", 
                       "DO996", "DO989", "DO988", "DO987", "DO983", "DO985", "DO269", 
                       "DO268", "DO266"]
        date_col: FoedselsDato_Barn
  ### Exclusion criteria
  # C-section
  - name: current_c_section
    key_column: b_cpr
    match_on: b_cpr
    time_window: during_pregnancy
    conditions:
      - condition:
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: MARKOER_KEJSERSNIT
        operator: "=="
        value: "1"
        date_col: FOEDSELSDATO
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Kejsersnit
        operator: "!="
        value: "-1"
        date_col: FoedselsDato_Barn
      - condition: or
        table: 
          table1: ${paths.input_dir_SDS}/kejsersnit.csv
          table2: ${paths.input_dir_SDS}/mfr.csv
          left_on: FK_MFR
          right_on: PK_MFR
        match_on: CPR_BARN
        column: SKSKODE
        operator: "startswith"
        value: "KMCA"
        date_col: FOEDSELSDATO
  # labor induction
  - name: current_induced_labor
    key_column: b_cpr
    match_on: b_cpr
    time_window: during_pregnancy
    conditions:
      - condition:
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: MARKOER_IGANGSAETTELSE
        operator: "=="
        value: "1"
        date_col: FOEDSELSDATO
      - condition: 
        table: 
          table1: ${paths.input_dir_SDS}/igangsaettelse.csv
          table2: ${paths.input_dir_SDS}/mfr.csv
          left_on: FK_MFR
          right_on: PK_MFR
        match_on: CPR_BARN
        column: SKSKODE
        operator: "startswith"
        value: ["KMAC", "BKHD"]
        date_col: FOEDSELSDATO
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Igangsaettelse_Ballonkateter
        operator: "=="
        value: "Ja"
        date_col: FoedselsDato_Barn
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Igangsaettelse_Medicinsk
        operator: "=="
        value: "Ja"
        date_col: FoedselsDato_Barn
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Igangsaettelse_HSP
        operator: "=="
        value: "Ja"
        date_col: FoedselsDato_Barn