population_save_path: /Users/zcr545/Desktop/Projects/repos/EHR_extract/population_${hydra:job.config_name}.json
discards_save_path: /Users/zcr545/Desktop/Projects/repos/EHR_extract/discards_${hydra:job.config_name}.json
distribution_save_path: /Users/zcr545/Desktop/Projects/repos/EHR_extract/distribution_${hydra:job.config_name}.json
imaging_metadata_save_path: /Users/zcr545/Desktop/Projects/repos/EHR_extract/imaging_metadata_${hydra:job.config_name}.csv

strict: True 

base_population: 
  table: /Users/zcr545/Desktop/Projects/repos/ehr2meds/data/raw/fetal_data/SDS_and_SP_from_population/population.csv
  column: CPR_BARN

conditional_criteria:
  # GA available at birth
  - action: include
    conditions: 
      - condition: 
        table: ehr2meds/data/raw/fetal_data/SDS_and_SP_from_population/MFR2_main.csv
        match_on: CPR_BARN
        column: GESTATIONSDAGE
        operator: ">"
        value: 0
      - condition: and
        table: ehr2meds/data/raw/fetal_data/SDS_and_SP_from_population/MFR2_main.csv
        match_on: CPR_BARN
        column: LEVENDE_ELLER_DOD
        operator: "!="
        value: Levende
        action: exclude
      - condition: or
        table: ehr2meds/data/raw/fetal_data/SDS_and_SP_from_population/MFR3_Nyfoedte.csv
        match_on: CPRNummer_Barn
        column: Gestationsalder
        operator: ">"
        value: 0
  # Not C-section (kejsersnit)
  - action: include
    conditions:
      - condition:
        table: ehr2meds/data/raw/fetal_data/SDS_and_SP_from_population/MFR3_Nyfoedte.csv
        match_on: CPRNummer_Barn
        column: Kejsersnit
        operator: "=="
        value: "-1"
      - condition: or
        table: ehr2meds/data/raw/fetal_data/SDS_and_SP_from_population/MFR2_main.csv
        match_on: CPR_BARN
        column: MARKOER_KEJSERSNIT
        operator: "!="
        value: "1"

custom_criteria:
  # Removes twin pregnancies AND close pregnancies
  - function: find_close_siblings
    args:
      table: ehr2meds/data/raw/fetal_data/SDS_and_SP_from_population/MFR2_main.csv
      match_on: CPR_BARN
      mom_column: CPR_MODER
      delivery_date_column: FOEDSELSDATO
      threshold_days: 280
    action: exclude
    
#imaging_matching_criteria:
#  # Scan-to-delivery interval
#  - function: find_images_and_timedeltas
#    args: 
#      table1: ehr2meds/data/raw/fetal_data/SDS_and_SP_from_population/MFR2_main.csv
#      table2: /Users/zcr545/Desktop/Projects/repos/EHR_extract/test_data/test_table.csv
#      child_id_column1: CPR_BARN
#      mom_id_column1: CPR_MODER
#      mom_id_column2: CPR_MOR
#      date_column1: FOEDSELSDATO
#      date_column2: studydate
#      ga_column1: GESTATIONSDAGE
#      min_diff_days_scan_to_delivery: -999999999999 #0
#      max_diff_days_scan_to_delivery: 999999999999 #210
#      min_diff_ga_scan_to_delivery: -999999999999 #196
#      max_diff_ga_scan_to_delivery: 999999999999 #259
#    action: include
