
population: 
  table: /Users/zcr545/Desktop/Projects/repos/ehr2meds/data/raw/fetal_data/SDS_from_population/population.csv
  column: CPR_BARN

inclusion_criteria:
  - table: /Users/zcr545/Desktop/Projects/repos/EHR_extract/test_data/test_table.csv
    match_on: CPR_BARN
    criteria:
      - column: GA_at_studydate_in_days
        operator: ">"
        value: 196
      - column: GA_at_studydate_in_days
        operator: "<"
        value: 259
  - table: ehr2meds/data/raw/fetal_data/SDS_from_population/MFR3_Nyfoedte.csv
    match_on: CPRNummer_Barn
    criteria:
      - column: Kejsersnit
        operator: "=="
        value: "-1"
  - table: ehr2meds/data/raw/fetal_data/SDS_from_population/MFR2_main.csv
    match_on: CPR_BARN
    criteria:
      - column: LEVENDE_ELLER_DOD
        operator: "!="
        value: Levende

exclusion_criteria:
  - table: ehr2meds/data/raw/fetal_data/SP_from_population/labtest.csv
    match_on: CPR
    multicolumn_criteria:
      - criteria: 
        - column: Enhed
          operator: "=="
          value: "U/L"
        - column: Resultatværdi
          operator: ">"
          value: 145     
      - criteria: 
        - column: Enhed
          operator: "=="
          value: "U/L"
        - column: Resultatværdi
          operator: "=="
          value: "påvist"  
