paths:
  input_dir_SDS: ehr2meds/data/raw/fetal_data/SDS_and_SP_from_population
  input_dir_SP: ehr2meds/data/raw/fetal_data/SDS_and_SP_from_population
  output_dir: /Users/zcr545/Desktop/Projects/repos/EHR_extract/outputs 
  population_save_path: ${paths.output_dir}/population_${hydra:job.config_name}.csv
  discards_save_path: ${paths.output_dir}/discards_${hydra:job.config_name}.json
  distribution_save_path: ${paths.output_dir}/distribution_${hydra:job.config_name}.json
  imaging_metadata_save_path: ${paths.output_dir}/imaging_metadata_${hydra:job.config_name}
  imaging_metadata_output_formats: ["csv",]

strict: True 

population: 
  population_key: CPR_BARN
  tables: 
    - table: ${paths.input_dir_SDS}/mfr.csv
      columns:
        CPR_BARN: CPR_BARN
        CPR_MOR: CPR_MODER
        GA: GESTATIONSALDER_DAGE
        Birthday: FOEDSELSDATO
      # Hospital: 
    - table: ${paths.input_dir_SDS}/nyfoedte.csv
      columns:
        CPR_BARN: CPRnummer_Barn
        CPR_MOR: CPRnummer_Mor
        GA: Gestationsalder
        Birthday: FoedselsDato_Barn
      # Hospital: 
  

conditional_criteria:
  # GA available at birth
  - action: include
    conditions: 
      - condition: 
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: GESTATIONSALDER_DAGE
        operator: ">"
        value: 0
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Gestationsalder
        operator: ">"
        value: 0
  # Only live birth
  - action: include
    conditions:
      - condition: 
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: LEVENDE_ELLER_DOEDFOEDT
        operator: "=="
        value: Levendefødt
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: LevendefoedtDoedfoedt
        operator: "=="
        value: "1"
  # Not C-section (kejsersnit)
  - action: include
    conditions:
      - condition:
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Kejsersnit
        operator: "=="
        value: "-1"
      - condition: or
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: MARKOER_KEJSERSNIT
        operator: "!="
        value: "1"
  # Not induced
  - action: exclude
    conditions:
      - condition:
        table: ${paths.input_dir_SDS}/mfr.csv
        match_on: CPR_BARN
        column: MARKOER_IGANGSAETTELSE
        operator: "=="
        value: "1"
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Igangsaettelse_Ballonkateter
        operator: "=="
        value: "Ja"
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Igangsaettelse_Medicinsk
        operator: "=="
        value: "Ja"
      - condition: or
        table: ${paths.input_dir_SDS}/nyfoedte.csv
        match_on: CPRnummer_Barn
        column: Igangsaettelse_HSP
        operator: "=="
        value: "Ja"

custom_criteria:
  # Removes twin pregnancies AND close pregnancies
  - function: find_close_births
    args:
      table: ${paths.input_dir_SDS}/nyfoedte.csv
      match_on: CPRnummer_Barn
      mom_column: CPRnummer_Mor
      birth_id_column: DW_EK_Foedsel
      delivery_date_column: FoedselsDato_Barn
      threshold_days: 280
    action: exclude
  - function: find_close_births
    args:
      table: ${paths.input_dir_SDS}/mfr.csv
      match_on: CPR_BARN
      mom_column: CPR_MODER
      birth_id_column: FOEDSELSLOEBENUMMER
      delivery_date_column: FOEDSELSDATO
      threshold_days: 280
    action: exclude
  #- function: find_multiple_pregnancies
  #  args:
  #    table: ${paths.input_dir_SDS}/nyfoedte.csv
  #    match_on: CPRnummer_Barn
  #    birth_id_column: DW_EK_Foedsel
  #  action: exclude
  #- function: find_multiple_pregnancies
  #  args:
  #    table: ${paths.input_dir_SDS}/mfr.csv
  #    match_on: CPR_BARN
  #    birth_id_column: FOEDSELSLOEBENUMMER
  #  action: exclude
imaging_matching_criteria:
  # Filter1: Scan-to-delivery interval
  # Filter2: GA at scan
  - function: find_images_and_timedeltas
    args: 
      table: /Users/zcr545/Desktop/Projects/repos/EHR_extract/test_data/test_table.csv
      child_id_column: cpr_child
      scan_date_column: study_date
      image_path_column: "file_path"
      min_diff_days_scan_to_delivery: -999999999999 #0
      max_diff_days_scan_to_delivery: 999999999999 #210
      min_ga_in_days_at_scan: -999999999999 #196
      max_ga_in_days_at_scan: 999999999999 #259
    action: include
  - function: find_images_with_predicted_classes
    # requires that "find_images_and_timedeltas" is run first to generate imaging metadata dataframe
    args:
      table: /Users/zcr545/Desktop/Projects/repos/EHR_extract/test_data/img_type.csv
      classes: [14]
      image_path_column: filename
      imaging_metadata_image_path_column: file_path 
      class_column: pred
      child_id_column: cpr_child
    action: include

