# @package _global_
defaults:
  - /default
  - _self_

paths:
  input_dir_SDS: /storage/archive/UCPH/DeepFetal/SDS/registers_pseudonymized
  input_dir_SP: /storage/archive/UCPH/DeepFetal/SP/tables
  input_dir_img_db: /projects/users/data/UCPH/DeepFetal/ultrasound/tables/database_snapshots
  split_dir: /projects/users/data/UCPH/DeepFetal/projects/common/splits
  output_dir: /projects/users/data/UCPH/DeepFetal/projects/common/splits/${hydra:job.config_name}

update_train_split: ${paths.split_dir}/split_V4/train_split_0.15_2026-06-08.csv
update_test_split: ${paths.split_dir}/split_V4/test_split_0.15_2026-06-08.csv

population: 
  population_key: CPR_MOR
  tables: 
    - table: ${paths.input_dir_SDS}/mfr.csv
      columns:
        CPR_MOR: CPR_MODER
    - table: ${paths.input_dir_SDS}/nyfoedte.csv
      columns:
        CPR_MOR: CPRnummer_Mor
    - table: ${paths.input_dir_SP}/Population.csv
      columns:
        CPR_MOR: MOR_CPR
    - table: ${paths.input_dir_img_db}/all_images_2026-06-23.csv
      columns:
        CPR_MOR: phair_hash
        
holdout_frac: 0.15
seed: 41290

