# @package _global_
defaults:
  - /default
  - _self_

paths:
  input_dir_SDS: /storage/archive/UCPH/DeepFetal/SDS/registers_pseudonymized
  input_dir_SP: /storage/archive/UCPH/DeepFetal/SP/tables
  output_dir: /projects/users/data/UCPH/DeepFetal/projects/common/splits/${hydra:job.config_name}

strict: True 

population: 
  population_key: CPR_MOR
  tables: 
    - table: /projects/users/data/UCPH/DeepFetal/projects/common/splits/legacy/CPRS_T21_Growth_pseudonymized.csv
      columns:
        CPR_MOR: cpr_hashed

        
holdout_frac: 0.15
seed: 41290

