# @package _global_
defaults:
  - /default
  - _self_

paths:
  input_dir_SDS: /storage/archive/UCPH/DeepFetal/SDS/registers_pseudonymized
  input_dir_SP: /storage/archive/UCPH/DeepFetal/SP/tables
  output_dir: /projects/users/data/UCPH/DeepFetal/projects/common/splits/${hydra:job.config_name}

strict: True 

population: 
  population_key: CPR_MOR
  tables: 
    - table: ${paths.input_dir_SDS}/mfr.csv
      columns:
        CPR_MOR: CPR_MODER
    - table: ${paths.input_dir_SDS}/nyfoedte.csv
      columns:
        CPR_MOR: CPRnummer_Mor
    - table: ${paths.input_dir_SP}/Population.csv
      columns:
        CPR_MOR: MOR_CPR
    - table: /projects/users/people/seblla/all_images_2026-05-29.csv
      columns:
        CPR_MOR: phair_hash
        
holdout_frac: 0.15
seed: 41290

